/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.4.v201511201313.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef COMMONAPI_DBUS_LEGACYINTERFACE_DEPLOYMENT_HPP_
#define COMMONAPI_DBUS_LEGACYINTERFACE_DEPLOYMENT_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace fake {
namespace legacy {
namespace service {
namespace LegacyInterface_ {

// Interface-specific deployment types

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments


} // namespace LegacyInterface_
} // namespace service
} // namespace legacy
} // namespace fake
} // namespace v1

#endif // COMMONAPI_DBUS_LEGACYINTERFACE_DEPLOYMENT_HPP_
