/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.1.v201505270851.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_TESTS_Test_Freedesktop_Interface_DBUS_STUB_ADAPTER_HPP_
#define COMMONAPI_TESTS_Test_Freedesktop_Interface_DBUS_STUB_ADAPTER_HPP_

#include <v1_0/commonapi/tests/TestFreedesktopInterfaceStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusFreedesktopStubAdapterHelper.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1_0 {
namespace commonapi {
namespace tests {

typedef CommonAPI::DBus::DBusStubAdapterHelper<TestFreedesktopInterfaceStub> TestFreedesktopInterfaceDBusStubAdapterHelper;

class TestFreedesktopInterfaceDBusStubAdapterInternal
    : public virtual TestFreedesktopInterfaceStubAdapter,
      public TestFreedesktopInterfaceDBusStubAdapterHelper
{
public:
    TestFreedesktopInterfaceDBusStubAdapterInternal(
            const CommonAPI::DBus::DBusAddress &_address,
            const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
            const std::shared_ptr<CommonAPI::StubBase> &_stub);

    ~TestFreedesktopInterfaceDBusStubAdapterInternal();

    virtual const bool hasFreedesktopProperties();

    void fireTestPredefinedTypeAttributeAttributeChanged(const uint32_t& value);
    void fireTestReadonlyAttributeAttributeChanged(const uint32_t& value);
    void fireTestDerivedStructAttributeAttributeChanged(const ::commonapi::tests::DerivedTypeCollection::TestStructExtended& value);
    void fireTestDerivedArrayAttributeAttributeChanged(const ::commonapi::tests::DerivedTypeCollection::TestArrayUInt64& value);



    const TestFreedesktopInterfaceDBusStubAdapterHelper::StubDispatcherTable& getStubDispatcherTable();
    const CommonAPI::DBus::StubAttributeTable& getStubAttributeTable();

    void deactivateManagedInstances();
    

static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        CommonAPI::Version
        > getTestFreedesktopInterfaceInterfaceVersionStubDispatcher;

static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        uint32_t
        > getTestPredefinedTypeAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        uint32_t
        > setTestPredefinedTypeAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        uint32_t
        > getTestReadonlyAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        ::commonapi::tests::DerivedTypeCollection::TestStructExtended
        > getTestDerivedStructAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        ::commonapi::tests::DerivedTypeCollection::TestStructExtended
        > setTestDerivedStructAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        ::commonapi::tests::DerivedTypeCollection::TestArrayUInt64
        > getTestDerivedArrayAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopInterfaceStub,
        ::commonapi::tests::DerivedTypeCollection::TestArrayUInt64
        > setTestDerivedArrayAttributeAttributeStubDispatcher;






 protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const;

 private:
    TestFreedesktopInterfaceDBusStubAdapterHelper::StubDispatcherTable stubDispatcherTable_;
    CommonAPI::DBus::StubAttributeTable stubAttributeTable_;
};

class TestFreedesktopInterfaceDBusStubAdapter
    : public TestFreedesktopInterfaceDBusStubAdapterInternal,
      public std::enable_shared_from_this<TestFreedesktopInterfaceDBusStubAdapter> {
public:
    TestFreedesktopInterfaceDBusStubAdapter(
    	const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub)
    	: CommonAPI::DBus::DBusStubAdapter(
    		_address, 
    		_connection,
            false),
          TestFreedesktopInterfaceDBusStubAdapterInternal(
          	_address, 
          	_connection, 
          	_stub) { 
    }
};

} // namespace tests
} // namespace commonapi
} // namespace v1_0

#endif // COMMONAPI_TESTS_Test_Freedesktop_Interface_DBUS_STUB_ADAPTER_HPP_
