/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.5.qualifier.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_TESTS_Extended_Interface_PROXY_BASE_H_
#define COMMONAPI_TESTS_Extended_Interface_PROXY_BASE_H_

#include "ExtendedInterface.h"
#include "TestInterfaceProxyBase.h"



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <vector>

#include <CommonAPI/Proxy.h>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace tests {

class ExtendedInterfaceProxyBase: virtual public TestInterfaceProxyBase {
 public:

    typedef std::function<void(const CommonAPI::CallStatus&)> TestIntMethodExtendedAsyncCallback;



    virtual void TestIntMethodExtended(const uint32_t& inInt, CommonAPI::CallStatus& callStatus) = 0;
    virtual std::future<CommonAPI::CallStatus> TestIntMethodExtendedAsync(const uint32_t& inInt, TestIntMethodExtendedAsyncCallback callback) = 0;
};

} // namespace tests
} // namespace commonapi

#endif // COMMONAPI_TESTS_Extended_Interface_PROXY_BASE_H_
