/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 2.1.5.qualifier.
* Used org.franca.core 0.8.10.201309262002.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef COMMONAPI_TESTS_Test_Freedesktop_Derived_Interface_DBUS_STUB_ADAPTER_H_
#define COMMONAPI_TESTS_Test_Freedesktop_Derived_Interface_DBUS_STUB_ADAPTER_H_

#include <commonapi/tests/TestFreedesktopDerivedInterfaceStub.h>
#include <commonapi/tests/TestFreedesktopInterfaceDBusStubAdapter.h>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusStubAdapterHelper.h>
#include <CommonAPI/DBus/DBusStubAdapter.h>
#include <CommonAPI/DBus/DBusFactory.h>
#include <CommonAPI/DBus/DBusServicePublisher.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace commonapi {
namespace tests {

typedef CommonAPI::DBus::DBusStubAdapterHelper<TestFreedesktopDerivedInterfaceStub> TestFreedesktopDerivedInterfaceDBusStubAdapterHelper;

class TestFreedesktopDerivedInterfaceDBusStubAdapterInternal: public virtual TestFreedesktopDerivedInterfaceStubAdapter, public TestFreedesktopDerivedInterfaceDBusStubAdapterHelper, public TestFreedesktopInterfaceDBusStubAdapterInternal {
 public:
    TestFreedesktopDerivedInterfaceDBusStubAdapterInternal(
            const std::shared_ptr<CommonAPI::DBus::DBusFactory>& factory,
            const std::string& commonApiAddress,
            const std::string& dbusInterfaceName,
            const std::string& dbusBusName,
            const std::string& dbusObjectPath,
            const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusConnection,
            const std::shared_ptr<CommonAPI::StubBase>& stub);

    ~TestFreedesktopDerivedInterfaceDBusStubAdapterInternal();

    virtual const bool hasFreedesktopProperties();

    void fireTestAttributedFromDerivedInterfaceAttributeChanged(const uint32_t& value);



    const TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::StubDispatcherTable& getStubDispatcherTable();
    const CommonAPI::DBus::StubAttributeTable& getStubAttributeTable();

    void deactivateManagedInstances();

    virtual const std::string getAddress() const {
        return DBusStubAdapter::getAddress();
    }

    virtual const std::string& getDomain() const {
        return DBusStubAdapter::getDomain();
    }

    virtual const std::string& getServiceId() const {
        return DBusStubAdapter::getServiceId();
    }

    virtual const std::string& getInstanceId() const {
        return DBusStubAdapter::getInstanceId();
    }

    virtual void init(std::shared_ptr<DBusStubAdapter> instance) {
        return TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::init(instance);
    }

    virtual void deinit() {
        return TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::deinit();
    }

    virtual bool onInterfaceDBusMessage(const CommonAPI::DBus::DBusMessage& dbusMessage) {
        return TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::onInterfaceDBusMessage(dbusMessage);
    }

    virtual bool onInterfaceDBusFreedesktopPropertiesMessage(const CommonAPI::DBus::DBusMessage& dbusMessage) {
        return TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::onInterfaceDBusFreedesktopPropertiesMessage(dbusMessage);
    }

static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        CommonAPI::Version
        > getTestFreedesktopDerivedInterfaceInterfaceVersionStubDispatcher;

static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        uint32_t
        > getTestAttributedFromDerivedInterfaceAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        uint32_t
        > setTestAttributedFromDerivedInterfaceAttributeStubDispatcher;

#ifdef WIN32
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        uint32_t
        > getTestPredefinedTypeAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        uint32_t
        > setTestPredefinedTypeAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        uint32_t
        > getTestReadonlyAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        DerivedTypeCollection::TestStructExtended
        > getTestDerivedStructAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        DerivedTypeCollection::TestStructExtended
        > setTestDerivedStructAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusGetFreedesktopAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        DerivedTypeCollection::TestArrayUInt64
        > getTestDerivedArrayAttributeAttributeStubDispatcher;
static CommonAPI::DBus::DBusSetFreedesktopObservableAttributeStubDispatcher<
        TestFreedesktopDerivedInterfaceStub,
        DerivedTypeCollection::TestArrayUInt64
        > setTestDerivedArrayAttributeAttributeStubDispatcher;
#endif


#ifdef WIN32
#endif


#ifdef WIN32
#endif

 protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const;

 private:
    TestFreedesktopDerivedInterfaceDBusStubAdapterHelper::StubDispatcherTable stubDispatcherTable_;
    CommonAPI::DBus::StubAttributeTable stubAttributeTable_;
};

class TestFreedesktopDerivedInterfaceDBusStubAdapter: public TestFreedesktopDerivedInterfaceDBusStubAdapterInternal, public std::enable_shared_from_this<TestFreedesktopDerivedInterfaceDBusStubAdapter> {
public:
    TestFreedesktopDerivedInterfaceDBusStubAdapter(
                         const std::shared_ptr<CommonAPI::DBus::DBusFactory>& factory,
                         const std::string& commonApiAddress,
                         const std::string& dbusInterfaceName,
                         const std::string& dbusBusName,
                         const std::string& dbusObjectPath,
                         const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusConnection,
                         const std::shared_ptr<CommonAPI::StubBase>& stub) :
            CommonAPI::DBus::DBusStubAdapter(
                            factory,
                            commonApiAddress,
                            dbusInterfaceName,
                            dbusBusName,
                            dbusObjectPath,
                            dbusConnection,
                            false),
            TestFreedesktopDerivedInterfaceDBusStubAdapterInternal(
                            factory,
                            commonApiAddress,
                            dbusInterfaceName,
                            dbusBusName,
                            dbusObjectPath,
                            dbusConnection,
                            stub) { }
};

} // namespace tests
} // namespace commonapi

#endif // COMMONAPI_TESTS_Test_Freedesktop_Derived_Interface_DBUS_STUB_ADAPTER_H_
