/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.1.v201505270851.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1_0/commonapi/tests/managed/RootInterfaceStubDefault.hpp>
#include <assert.h>

namespace v1_0 {
namespace commonapi {
namespace tests {
namespace managed {

RootInterfaceStubDefault::RootInterfaceStubDefault():
        remoteEventHandler_(this),
        autoInstanceCounter_(0),
        interfaceVersion_(RootInterface::getInterfaceVersion()) {
}

const CommonAPI::Version& RootInterfaceStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    return interfaceVersion_;
}

RootInterfaceStubRemoteEvent* RootInterfaceStubDefault::initStubAdapter(const std::shared_ptr<RootInterfaceStubAdapter> &_adapter) {
    CommonAPI::Stub<RootInterfaceStubAdapter, RootInterfaceStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void RootInterfaceStubDefault::testRootMethod(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _inInt, std::string _inString, testRootMethodReply_t _reply) {
    RootInterface::testRootMethodError error;
    int32_t outInt;
    std::string outString;
    _reply(error, outInt, outString);
}



bool RootInterfaceStubDefault::registerManagedStubLeafInterfaceAutoInstance(std::shared_ptr<LeafInterfaceStub> _stub) {
    autoInstanceCounter_++;
    std::stringstream ss;
    ss << stubAdapter_->getAddress().getInstance() << ".i" << autoInstanceCounter_;
    std::string instance = ss.str();
    assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubLeafInterface(_stub, instance);
}
bool RootInterfaceStubDefault::registerManagedStubLeafInterface(std::shared_ptr<LeafInterfaceStub> _stub, const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubLeafInterface(_stub, _instance);
}
bool RootInterfaceStubDefault::deregisterManagedStubLeafInterface(const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->deregisterManagedStubLeafInterface(_instance);
}
std::set<std::string>& RootInterfaceStubDefault::getLeafInterfaceInstances() {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->getLeafInterfaceInstances();
}
bool RootInterfaceStubDefault::registerManagedStubBranchInterfaceAutoInstance(std::shared_ptr<BranchInterfaceStub> _stub) {
    autoInstanceCounter_++;
    std::stringstream ss;
    ss << stubAdapter_->getAddress().getInstance() << ".i" << autoInstanceCounter_;
    std::string instance = ss.str();
    assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubBranchInterface(_stub, instance);
}
bool RootInterfaceStubDefault::registerManagedStubBranchInterface(std::shared_ptr<BranchInterfaceStub> _stub, const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubBranchInterface(_stub, _instance);
}
bool RootInterfaceStubDefault::deregisterManagedStubBranchInterface(const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->deregisterManagedStubBranchInterface(_instance);
}
std::set<std::string>& RootInterfaceStubDefault::getBranchInterfaceInstances() {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->getBranchInterfaceInstances();
}

RootInterfaceStubDefault::RemoteEventHandler::RemoteEventHandler(RootInterfaceStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace managed
} // namespace tests
} // namespace commonapi
} // namespace v1_0
