/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.1.v201505270851.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include "RootInterface.hpp"

namespace v1_0 {
namespace commonapi {
namespace tests {
namespace managed {

#ifndef WIN32
const int32_t RootInterface::testRootMethodError::OK;
const int32_t RootInterface::testRootMethodError::NOTOK;
#endif


} // namespace managed
} // namespace tests
} // namespace commonapi
} // namespace v1_0
