name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ubuntu-22.04]
    
    steps: 
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Checkout capicxx-core-runtime"
      uses: actions/checkout@v3 
      with:
        repository: COVESA/capicxx-core-runtime
        path: 'capicxx-core-runtime'

    - name: "Install dbus"
      run: |
        wget http://dbus.freedesktop.org/releases/dbus/dbus-1.13.6.tar.gz
        tar -xzf dbus-1.13.6.tar.gz
        for patch in src/dbus-patches/*.patch
        do
        	patch -d dbus-1.13.6 -Np1 -i "$PWD/$patch" || continue
        done
        
        cmake -B build-dbus/libdbus -D DBUS_BUILD_TESTS=N -D CMAKE_INSTALL_PREFIX=install -S dbus-1.13.6/cmake
        cmake --build build-dbus/libdbus
        cmake --install build-dbus/libdbus --strip

    - name: "Build capicxx-core-runtime"
      run: |
        cmake -S capicxx-core-runtime -B build-core-runtime -DCMAKE_INSTALL_PREFIX=install
        cmake --build build-core-runtime --target install      

    - name: "Build capicxx-dbus-runtime"
      run: |
          cmake -S . -B build-dbus-runtime -DCMAKE_PREFIX_PATH=install
          cmake --build build-dbus-runtime
