/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.2.v201506150834.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1_0/commonapi/tests/managed/SecondRootStubDefault.hpp>
#include <assert.h>

namespace v1_0 {
namespace commonapi {
namespace tests {
namespace managed {

SecondRootStubDefault::SecondRootStubDefault():
        remoteEventHandler_(this),
        autoInstanceCounter_(0),
        interfaceVersion_(SecondRoot::getInterfaceVersion()) {
}

const CommonAPI::Version& SecondRootStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    return interfaceVersion_;
}

SecondRootStubRemoteEvent* SecondRootStubDefault::initStubAdapter(const std::shared_ptr<SecondRootStubAdapter> &_adapter) {
    CommonAPI::Stub<SecondRootStubAdapter, SecondRootStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}




bool SecondRootStubDefault::registerManagedStubLeafInterfaceAutoInstance(std::shared_ptr<LeafInterfaceStub> _stub) {
    autoInstanceCounter_++;
    std::stringstream ss;
    ss << stubAdapter_->getAddress().getInstance() << ".i" << autoInstanceCounter_;
    std::string instance = ss.str();
    assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubLeafInterface(_stub, instance);
}
bool SecondRootStubDefault::registerManagedStubLeafInterface(std::shared_ptr<LeafInterfaceStub> _stub, const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->registerManagedStubLeafInterface(_stub, _instance);
}
bool SecondRootStubDefault::deregisterManagedStubLeafInterface(const std::string &_instance) {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->deregisterManagedStubLeafInterface(_instance);
}
std::set<std::string>& SecondRootStubDefault::getLeafInterfaceInstances() {
	assert(stubAdapter_ !=NULL);
    return stubAdapter_->getLeafInterfaceInstances();
}

SecondRootStubDefault::RemoteEventHandler::RemoteEventHandler(SecondRootStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace managed
} // namespace tests
} // namespace commonapi
} // namespace v1_0
